import React from "react";
import SummarySettingsDropdown from "./SummarySettingsDropdown";
import FeedbackButton from "./FeedbackButton";
import { useLanguage } from "../context/LanguageContext";
import ContextGenerator from "./ContextGenerator";


function SummaryBlock({ summary, summaryLoading, summaryError, id, summaryLanguage, setSummaryLanguage, tone, setTone }) {
    const { language} = useLanguage();


    return (
        <div className="flex flex-col my-4 p-4 text-lg bg-[var(--color-light-turquoise)] rounded-xl">                                                                                                
            <h2 className="text-xl font-semibold underline my-2">Summary</h2>
            <div className="py-4 mb-2">
                {summaryLoading ? (
                    <p className="text-sm text-gray-500">Loading summary...</p>
                ) : summaryError ? (
                    <p className="text-sm text-red-500">Error: {summaryError}</p>
                ) : (
                    <p className="py-2">{summary?.synopsis}</p>
                )}
            </div>
            
            <h2 className="text-xl font-semibold underline my-2">Impact</h2>
            <div className="py-4 mb-2">
                {summaryLoading ? (
                    <p className="text-sm text-gray-500">Loading implications...</p>
                ) : summaryError ? (
                    <p className="text-sm text-red-500">Error: {summaryError}</p>
                ) : (
                    <p className="py-2">{summary?.implications}</p>
                )}
            </div>
    
            <div className="px-8 my-4 flex justify-between items-start">
                <SummarySettingsDropdown
                    language={language}
                    summaryLanguage={summaryLanguage}
                    setSummaryLanguage={setSummaryLanguage}
                    tone={tone}
                    setTone={setTone}
                />
                <ContextGenerator language={language} articleID={id} />
                <FeedbackButton language={language} articleID={id} />
            </div>
                                
            {/* disclaimer */}
            <p className="text-[var(--color-text-lightgrey)] text-xs mt-8 py-2">
                {language === "zh-Hant" ? "此摘要由 SearcherAI 生成。" 
                : language === "zh-Hans" ? "此摘要由 SearcherAI 生成。" 
                : "This summary is generated by SearcherAI."}
            </p>                    
        </div>
    );
}

export default SummaryBlock;