import React from "react";
import SummarySettingsDropdown from "./SummarySettingsDropdown";
import FeedbackButton from "./FeedbackButton";
import { useLanguage } from "../context/LanguageContext";
import ContextGenerator from "./ContextGenerator";


function SummaryBlock({ summary, summaryLoading, summaryError, id, summaryLanguage, setSummaryLanguage, tone, setTone }) {
    const { language} = useLanguage();


    return (
        <div className="flex flex-col justify-between my-4 p-4 text-lg bg-[var(--color-light-turquoise)] rounded-lg">                                                                                                
            <ul className="list-inside">
                <li className="py-4">
                    {summaryLoading ? (
                        <p className="text-sm text-gray-500">Loading summary...</p>
                    ) : summaryError ? (
                        <p className="text-sm text-[var(--color-secondary-1)]">Error: {summaryError}</p>
                    ) : (
                        <p className="py-2">{summary?.synopsis}</p>
                    )}
                </li>
                
                <li className="py-4">
                    {summaryLoading ? (
                        <p className="text-sm text-gray-500">Loading implications...</p>
                    ) : summaryError ? (
                        <p className="text-sm text-red-500">Error: {summaryError}</p>
                    ) : (
                        <p className="py-2">{summary?.implications}</p>
                    )}
                </li>
            </ul>
            
            <div className="my-4 flex items-start justify-between">
                <SummarySettingsDropdown
                    language={language}
                    summaryLanguage={summaryLanguage}
                    setSummaryLanguage={setSummaryLanguage}
                    tone={tone}
                    setTone={setTone}
                />
                <ContextGenerator language={language} articleID={id} />
            </div>
            {/* disclaimer */}
            <div className="relative flex justify-between gap-4">
                <p className="text-[var(--color-text-lightgrey)] text-xs py-2">
                    {language === "zh-Hant" ? "此摘要由 SearcherAI 生成。" 
                    : language === "zh-Hans" ? "此摘要由 SearcherAI 生成。" 
                    : "This summary is generated by SearcherAI."}
                </p>       
                <FeedbackButton language={language} articleID={id} />          
            </div>  
                                
                         
        </div>
    );
}

export default SummaryBlock;