import React, { useState, useEffect } from "react";
import SplitBar from "../metric-components/SplitBar";
import SentimentExplanation from "../metric-components/SentimentExplanation";
import Ads from "../home-components/Ads";
import { useParams, useLocation } from "react-router-dom";
import SentimentGauge from "../metric-components/SentimentGauge";
import SubjectivitySlider from "../metric-components/SubjectivitySlider";
import { useLanguage } from "../context/LanguageContext";
import { Link } from "react-router-dom";
import OutletDistribution from "../metric-components/OutletDistribution";
import { FaRegBookmark , FaBookmark} from "react-icons/fa";
import { fetchArticle } from "../services/articleService";


function ViewArticle() {
    const { id } = useParams();
    const { language } = useLanguage();
    const location = useLocation();
    const article = location.state?.article;
    const [error, setError] = useState(null);
    const [bookmarked, setBookmarked] = useState(false);

    const handleBookmark = () => {
        setBookmarked(prevState => !prevState); // Toggle the current value

    };

    if (error) return <div className="text-red-500 text-center py-8">Error: {error}</div>;
    if (!article) return <div className="text-center py-8">Article not found.</div>;

    {console.log(article)}

    function getHoursAgo(dateString) {
        const articleDate = new Date(dateString);
        const now = new Date();
        const diffMs = now - articleDate;
        const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
        return diffHours;
    }

    return (
        <article className="grid grid-cols-[3fr_1fr_1fr] overflow-hidden justify-center items-start w-[90dvw] h-full mx-auto">
            { /* first column: article itself */}
            <div className="min-h-dvh px-1 py-4">
                { /* article title and image */ }
                <div className="flex-col flex-grow w-9/10 mx-auto">
                    {/* region, sector, date and time*/}
                    <div className="flex justify-between items-center my-1">
                        <div className="flex text-[var(--color-primary)] text-sm">
                            <label>{article.region}</label>
                            <label className="mx-2">|</label>
                            <label>{article.sector}</label>
                        </div>
                        <div className="text-[var(--color-text-lightgrey)] text-sm">
                            {article.date.slice(11,16)}                            
                            <span className="mr-4">,</span>
                            {article.date.slice(5, 10)}
                            <span>-</span>
                            {article.date.slice(0, 4)}
                        </div>
                    </div>                                        
                    <img src={article.pictureURL} className="w-full" />
                    <div className="w-full flex justify-between">
                        <h1 className="text-3xl font-semibold my-2">{article.title}</h1>
                        <button className="px-2" aria-label={bookmarked ? "Remove bookmark" : "Add bookmark"} onClick={handleBookmark}>
                            {bookmarked ? (
                                <FaBookmark className="text-2xl text-[var(--color-accent)] fill-current" />  ) : (
                                <FaRegBookmark className="text-2xl text-[var(--color-text-lightgrey)] hover:text-[var(--color-text-darkgrey)]" />
                            )}
                        </button>                  
                    </div>
                </div>

                {/* summaries */}
                <div className="flex flex-col w-9/10 mx-auto py-4 px-1 bg-[var(--color-summary-background)] border border-[var(--color-dark-turquoise)] rounded-xl">                                                                                
                    <div className="py-4">
                        <h2 className="text-xl font-bold mb-4">{language === "zh-Hant" ? "摘要" : language === "zh-Hans" ? "摘要" : "Summary"}</h2>
                        <p>{article.description}</p>                      
                    </div>                                               
                    <p className="text-[var(--color-text-lightgrey)] text-xs">This summary is generated by SearcherAI.</p>
                </div>

                {/* linked articles */}
                <div className="flex flex-col w-9/10 mx-auto py-4 px-1 border border-[var(--color-dark-turquoise)] ">                                                                                
                    <div className="py-4">
                        <h2 className="text-xl font-bold mb-4">{language === "zh-Hant" ? "文章一覽" : language === "zh-Hans" ? "文章一览" : "Article List"}</h2>
                        <ul>
                            {article.articles.map((publisherArticle, index) => (

                                <div key={index} className="flex justify-between items-start px-2 py-4">
                                    {/* image on the left, source + stance + title on the right */}
                                    {/* right side: source + stance on top, title below */}
                                    <img src={publisherArticle.publisherIcon} width={60} className="rounded-full"/>
                                    <div className="w-full px-4">
                                    <Link to={`/article/${publisherArticle.articleID}`} state={{ article:publisherArticle }}>                                                
                                        <div className="flex text-[var(--color-text-lightgrey)] text-sm gap-4">
                                            {publisherArticle.publisherName}
                                            <div className="px-2  bg-[var(--color-bg-grey)]">
                                                {publisherArticle.publisherStance}
                                            </div>                                        
                                        </div>            
                                        <h2 className="my-2 text-lg">{publisherArticle.title}</h2>                                             
                                    </Link>
                                    </div>                                    
                                </div>
                            ))}                                                                    
                        </ul>                     
                    </div>                                               
                    <p className="text-[var(--color-text-lightgrey)] text-xs">This summary is generated by SearcherAI.</p>
                </div>

                { /* number of sources, date*/}     
                <div className="w-9/10 mx-auto flex items-center">
                    <p className="text-xs whitespace-nowrap">
                        {article.nSources}
                        {language === 'zh-Hant' ? '篇文章' : language === 'zh-Hans' ? '篇文章' : ' articles'}
                    </p>
                    <label className="mx-2"> · </label>
                    <p className="text-xs whitespace-nowrap">
                        {getHoursAgo(article.date)}
                        {language === 'zh-Hant' ? '小時前' : language === 'zh-Hans' ? '小时前' : ' hours ago'}
                    </p>
                </div>                        
            </div>

            { /* second column: distribution, sentiment, subjectivity */}
            <div className="flex-col flex-grow justify-center min-h-dvh py-6 px-1">
                <div className="w-11/12 mx-auto border-b border-[var(--color-line-grey)]">
                    <h1 className="font-bold text-xl">Leaning distribution</h1>
                    <div className="mt-4 my-2">
                        <Link to="/user-guide">
                            <SplitBar cPercent={article.coverage.percentage.centric*100} pPercent={article.coverage.percentage.progressive*100} />
                        </Link>
                    </div>
                    
                    <div className="my-4">
                        <OutletDistribution cPercent={article.coverage.percentage.centric*100} pPercent={article.coverage.percentage.progressive*100}/>
                    </div>
                    <div className="my-4">
                        <SentimentExplanation sentiment={"Stats for distribution"} />
                    </div>
                </div>  
                <div className="w-9/10 mx-auto my-2">
                    <h1 className="font-bold text-xl">Metric analysis</h1>  
                    <div className="my-12">
                        <div className="my-4">
                            <SentimentGauge sentiment={article.metrics.sentiment}/>
                        </div>
                        <div className="mb-4 mt-12">
                            <SentimentExplanation sentiment={"Elaboration"} />
                        </div>                
                    </div>   
                    <div className="my-18">
                        <div className="mt-4 mb-2">
                            <SubjectivitySlider subjScore={article.metrics.subjectivity}/>
                        </div>               
                    </div>                  
                </div>                            
            </div>
            { /* third column: ads */}
            <div className="min-h-dvh h-full py-6 px-1 border-l border-[var(--color-line-darkgrey)]">
                <div className="flex flex-col flex-grow">
                    <img src="/src/assets/customise-ads-button.svg" className="w-1/2 mx-auto" />
                    {/* make it a button */}
                    <div className="h-[50vh] my-4">
                        <Ads />                       
                    </div>
                    <div className="h-[50vh] my-4">
                        <Ads />                       
                    </div>
                    
                </div>                
            </div>
        </article>                
    )        

}

export default ViewArticle